### ISSUE TITLE
Typogrify makes changes which should be accepted, but...

### ISSUE THREAD

**Issue by drgrigg** [rosstcarter/zane-grey_betty-zane#6]
You need to re-run `se typogrify .` as it makes changes which should be accepted.

But... I believe according to the manual [here](https://standardebooks.org/manual/1.6.2/single-page#8.7.7.8.4) that the word "damn" throughout should be 'bowdlerised' with a two-em dash not a one-em dash, as it's a partially obscured word.

Eg: it should be `D⁠⸺⁠n` not `D⁠—n` . You'll need to make this change before you re-run typogrify.

**Comment by rosstcarter** [comment]
se typogrify made no changes, so it won’t be reflected in a commit. Just want to let you know I did run it.

Ross
