### ISSUE TITLE
Semanticate makes a change which should be accepted

### ISSUE THREAD

**Issue by drgrigg** [rosstcarter/zane-grey_betty-zane#7]
You need to re-run `se semanticate .` and accept the added `<abbr>` tags it adds.

**Comment by rosstcarter** [comment]
Thank you for your thorough and exacting review. It is that level of quality control that attracted me to Standard Ebooks in the first place. I will do a git interactive rebase tomorrow.

Cheers,

Ross Carter

**Comment by rosstcarter** [comment]
Done
