### ISSUE TITLE
Modernize-spelling makes changes which should be accepted (all except one)

### ISSUE THREAD

**Issue by drgrigg** [rosstcarter/zane-grey_betty-zane#8]
You should run `se modernize-spelling .` again and accept all the changes except the one in Chapter 10 ("Hel-lo" is deliberate in the page scans). Commit the changes with "[Editorial] modernize hypenation and spelling". This one DOES require the "[Editorial]" in the commit message.

**Comment by rosstcarter** [comment]
Done
